---
title: "COVID analysis"
author: "Jon Yearsley"
date: "4/3/2020"
output: github_document
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("~/git_repos/corona/")

library(readxl)
library(ggplot2)
library(zoo)
```


Data downloaded from https://www.ecdc.europa.eu/sites/default/files/documents/COVID-19-geographic-disbtribution-worldwide.xlsx

```{r}
d = read_excel("COVID-19-geographic-disbtribution-worldwide.xlsx")
d$countriesAndTerritories = as.factor(d$countriesAndTerritories)
d$julian = as.numeric(julian(d$dateRep))
d$ID = c(1:nrow(d))

# Order deaths by time
ind = order(d$julian, d$countriesAndTerritories) 
d = d[ind,]

d$cumdeaths = ave(d$deaths, 
                  d$countriesAndTerritories, 
                  FUN=function(x){cumsum(x)})
```


Find day when number of new cases exceeded 3
```{r}
dplus = subset(d, cases>100)
startDate = aggregate(julian~countriesAndTerritories + 
                        geoId + 
                        countryterritoryCode, 
                      data=dplus, 
                      FUN=function(x) {min(x)})

ind = match(dplus$countryterritoryCode,
            startDate$countryterritoryCode)
dplus$daysIn = dplus$julian - startDate$julian[ind]
```


Select data from some countries
```{r}
country = c('Ireland',
            'Italy',
            'Sweden',
            'United_Kingdom',
            'Netherlands', 
            'Germany')

d2 = subset(dplus, 
            countriesAndTerritories %in% country)
```

Calculate 7 day roling averages
```{r}
for (i in 1:length(country)) {
  tmp=subset(d2, countriesAndTerritories==country[i])
  tmp$deaths_7day = rollmean(tmp$deaths, k=7, align='right', fill=NA)
  tmp$cumdeaths_7day = rollmean(tmp$cumdeaths, k=7, align='right', fill=NA)
  tmp$cases_7day = rollmean(tmp$cases, k=7, align='right', fill=NA)
  
  if (i==1) {
    d3 = tmp
  } else {
    d3 = rbind(d3, tmp)
  }
}
```


Plot the epidemic
```{r , echo=FALSE}
ggplot(data=d3,
       aes(x=daysIn, 
           y=cases_7day, 
           colour=countriesAndTerritories)) +
  geom_point() + 
  geom_smooth(method = 'loess', 
              span=1.5) +
  scale_y_log10() +
  scale_color_brewer(palette = 'Set1') +
  theme_bw() + 
  labs(x='Days post cases >100',
       y='Number of cases (7 day moving average)')
```

```{r message=FALSE, echo=FALSE}
ggplot(data=d3,
       aes(x=daysIn, 
           y=deaths_7day, 
           colour=countriesAndTerritories)) +
  geom_point() + 
  geom_smooth(method = 'loess', 
              span=1.5) +
  scale_y_log10() +
  scale_color_brewer(palette = 'Set1') +
  theme_bw() + 
  labs(x='Days post cases >100',
       y='Number of deaths (7 day moving average)')
```


```{r message=FALSE, echo=FALSE}
ggplot(data=d3,
       aes(x=cumdeaths_7day, 
           y=deaths_7day, 
           colour=countriesAndTerritories)) +
  geom_point() + 
  geom_smooth(method = 'loess', 
              span=1.5) +
  scale_y_log10() +
  scale_x_log10() +
  scale_color_brewer(palette = 'Set1') +
  theme_bw() + 
  labs(x='Cumulative number of deaths (7 day moving average)',
       y='Number of deaths (7 day moving average)')
```



```{r message=FALSE, echo=FALSE}
ggplot(data=d3,
       aes(y=deaths_7day/cases_7day, 
           x=daysIn, 
           colour=countriesAndTerritories)) +
  geom_point() + 
  geom_smooth(method = 'loess', 
              span=1.5) +
  scale_color_brewer(palette = 'Set1') +
  theme_bw() + 
  labs(y='Deaths / Cases (7 day average)',
       x='Days post 100 cases')
```
